name: hw workflow - Develop
on: [push]
jobs:
    say-hw:
        runs-on: ubuntu-latest
        steps:
            - name: Say-hw
              run: echo "Verison of app is latest - develop branch"
    
